[package]
name = "pegast"
version = "0.1.0"
authors = ["Janito Vaqueiro Ferreira Filho <janito.vff@gmail.com>"]
edition = "2018"

[features]
derive = ["pegast-derive"]

[dependencies]
pegast-derive = { path = "./derive", optional = true }
